print('-------------Operadores aritméticos-------------')
print('+ = Adição')
print('- = Subtração')
print('* = Multiplicação')
print('/ = Divisão')
print('** = Potencia')
print('// = Divisão inteira')
print('% = Resto da divisão')

print('-------------Ordem de Precedência-------------')
print('1-()')
print('2-**')
print('3-*, /, //, % ')
print('+, -')
