print('----------Desafio 04----------')
print('1-faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações '
      'possiveis sobre ela')
n3 = input('\nDigite algo para ser analisado:\n')
print(type(n3))
print('Verifica se está em Alfanumérico: {}'.format(n3.isalnum()))
print('Verifica se é Alfabetico: {}'.format(n3.isalpha()))
print('Verifica se todos caracteres são decimais: {}'.format(n3.isdecimal()))
print('Verifica se é os caracteres são dígitos: {}'.format(n3.isdigit()))
print('Verifica se a string for um identificador válido no Python: {}'.format(n3.isidentifier()))
print('Verifica se está em minúsculo: {}'.format(n3.islower()))
print('Verifica se os caracteres são numéricos: {}'.format(n3.isnumeric()))
print('Verifica se todos os caracteres da string forem imprimíveis ou se a string estiver vazia: {}'.format(n3.isprintable()))
print('Verifica se é um espaço: {}'.format(n3.isspace()))
print('Verifica se a sequência for uma sequência com título: {}'.format(n3.istitle()))
print('Verifica se está em Maiúsculo: {}'.format(n3.isupper()))
