print('9-Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada')
numerointeiro = int(input('Digite um valor para ver a sua tabuada:'))
print(f'{numerointeiro}x  1 = {numerointeiro*1}')
print(f'{numerointeiro}x  2 = {numerointeiro*2}')
print(f'{numerointeiro}x  3 = {numerointeiro*3}')
print(f'{numerointeiro}x  4 = {numerointeiro*4}')
print(f'{numerointeiro}x  5 = {numerointeiro*5}')
print(f'{numerointeiro}x  6 = {numerointeiro*6}')
print(f'{numerointeiro}x  7 = {numerointeiro*7}')
print(f'{numerointeiro}x  8 = {numerointeiro*8}')
print(f'{numerointeiro}x  9 = {numerointeiro*9}')
print(f'{numerointeiro}x 10 = {numerointeiro*10}')
